set(OMR_FOLDER "")
if (OMR_FOLDER STREQUAL  "")
  message("OMR FOLDER is unset, setting automatically")
  set (OMR_FOLDER ${PROJECT_SOURCE_DIR}/third_party/omr/)
  message("OMR FOLDER is set to ${OMR_FOLDER}")
endif()
list(APPEND CMAKE_MODULE_PATH
  ${OMR_FOLDER}cmake/modules/
)
set(OMR_DDR OFF CACHE BOOL "Enable DDR")
set(OMR_EXAMPLE OFF CACHE BOOL "")
set(OMR_COMPILER  ON CACHE BOOL "")
set(OMR_JITBUILDER ON CACHE BOOL "")
set(OMR_GC OFF CACHE BOOL "")
set(OMR_PORT ON CACHE BOOL "")
set(OMR_THREAD ON CACHE BOOL "")
set(OMR_TEST_COMPILER OFF CACHE BOOL "")
set(OMR_OMRSIG OFF CACHE BOOL "")
set(OMR_FVTEST OFF CACHE BOOL "")
set(OMR_GC_SEGREGATED_HEAP OFF CACHE BOOL "")
set(OMR_GC_MODRON_SCAVENGER OFF CACHE BOOL "")
set(OMR_GC_MODRON_CONCURRENT_MARK OFF CACHE BOOL "")
set(OMR_THR_CUSTOM_SPIN_OPTIONS OFF CACHE BOOL "")
set(OMR_NOTIFY_POLICY_CONTROL OFF CACHE BOOL "")
set(OMR_THR_SPIN_WAKE_CONTROL OFF CACHE BOOL "")
set(OMR_THR_SPIN_CODE_REFACTOR OFF CACHE BOOL "")
set(OMR_THR_FORK_SUPPORT OFF CACHE BOOL "")
set(OMR_WARNINGS_AS_ERRORS ON CACHE BOOL "")
set(OMR_AOT ON CACHE BOOL "")

set(OMR_SHARED_CACHE_MODS ON CACHE BOOL "")
set(WASM_SHARED_CACHE OFF CACHE BOOL "")
set(OMR_SHARED_CACHE OFF CACHE BOOL "")
set(OMR_ELF_SHARED_OBJECT OFF CACHE BOOL "")

if(WASM_SHARED_CACHE)
  add_definitions(-DWASM_SHARED_CACHE)
endif()

if(OMR_ELF_SHARED_OBJECT)
  add_definitions(-DOMR_ELF_SHARED_OBJECT)
endif()

function(add_omr_aot_and_jit)
  # Disable warnings when building all OMR components since OMR is more lax about some warnings.
  # Since this logic is inside a function, this only applies within the scope of the OMR CMake
  # files.
  cmake_policy(SET CMP0012 NEW)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -w")
  set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/third_party/omr/cmake/modules" ${CMAKE_MODULE_PATH})
  include(OmrTargetSupport)
  include(OmrPlatform)
  include(OmrCompilerSupport)
  add_subdirectory(${OMR_FOLDER}/example/glue EXCLUDE_FROM_ALL)
  add_subdirectory(${OMR_FOLDER} EXCLUDE_FROM_ALL)
  add_subdirectory(src/jit)
  add_subdirectory(src/aot)
  target_link_libraries(wabt PUBLIC wabtaotcomp)
  target_link_libraries(wabt PUBLIC wabtjit)
  target_link_libraries(wabt PUBLIC ffi)
endfunction()